name: Update Forks

on:
  workflow_dispatch: 

jobs:
  update-forks:
    runs-on: ubuntu-latest
    environment: test
    
    steps:
      - name: Set up GitHub CLI authentication
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Autenticación configurada para GitHub CLI"

      - name: Create pull requests in forks
        run: |
          # Lista de repositorios de estudiantes (forks)
          repos=(
            danthb/intro-computer-vision
          )

          # Mensaje del Pull Request
          PR_TITLE="Actualizar con los últimos cambios del template"
          PR_BODY="Se han realizado las siguientes actualizaciones:\n- Corrección de errores\n- Nuevas instrucciones para la tarea"

          for repo in "${repos[@]}"; do
            gh pr create --repo "$repo" --head "tu-organizacion:main" --base "main" \
              --title "$PR_TITLE" --body "$PR_BODY"
          done
